AWSTemplateFormatVersion: 2010-09-09
Description: "CI/CD infrastructure for a simple calculator application"
Parameters:
  codeBucket:
    Description: S3 Bucket where functions.zip and calculator.zip are stored.
    Type: String
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: "CI-CD"
  VpcCIDR:
    Description: IP range (CIDR notation) for the VPC
    Type: String
    Default: "192.168.0.0/16"
    AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([1][6-9]|[2][0-8]))$
  PublicSubnet1CIDR:
    Description: IP range (CIDR notation) for the PUBLIC subnet in the FIRST Availability Zone
    Type: String
    Default: "192.168.0.0/20"
    AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([1][6-9]|[2][0-8]))$
  PrivateSubnet1CIDR:
    Description: IP range (CIDR notation) for the PRIVATE subnet in the SECOND Availability Zone
    Type: String
    Default: "192.168.64.0/20"
    AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([1][6-9]|[2][0-8]))$
  PublicSubnet2CIDR:
    Description: IP range (CIDR notation) for the PUBLIC subnet in the SECOND Availability Zone
    Type: String
    Default: "192.168.16.0/20"
    AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([1][6-9]|[2][0-8]))$
  ApplicationName:
    Description: An application name that will be prefixed to resource names
    Type: String
    Default: simple-calculator
  LatestAmiId:
    Description: The AWS::EC2::Image::Id that will be pulled from parameter store to be used for application instances
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
  OutputsPrefix:
    Description: The prefix for stack outputs that will be used for your pipeline resources
    Type: String
    Default: shared-resources
Metadata:
  # Parameter formatting to help explain what parameters need to be changed.
  # codeBucket is the only parameter not having a default value because in this project I
  # create the S3 bucket and upload the files (functions.zip and calculator.zip) using the
  # AWS CLI from my local machine.
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required Parameters
      Parameters:
      - codeBucket
    - Label:
        default: Other Parameters
      Parameters:
      - EnvironmentName
      - VpcCIDR
      - PublicSubnet1CIDR
      - PublicSubnet2CIDR
      - PrivateSubnet1CIDR
      - ApplicationName
      - LatestAmiId
      - OutputsPrefix
    ParameterLabels:
      codeBucket:
        default: Bucket where functions.zip and calculator.zip are stored
      EnvironmentName:
        default: An environment name that will be prefixed to resource names
      VpcCIDR:
        default: IP range (CIDR notation) for the VPC
      PublicSubnet1CIDR:
        default: IP range (CIDR notation) for the PUBLIC subnet in the FIRST Availability Zone
      PublicSubnet2CIDR:
        default: IP range (CIDR notation) for the PUBLIC subnet in the SECOND Availability Zone
      PrivateSubnet1CIDR:
        default: IP range (CIDR notation) for the PRIVATE subnet in the SECOND Availability Zone
      ApplicationName:
        default: An application name that will be prefixed to resource names
      LatestAmiId:
        default: The AWS::EC2::Image::Id that will be pulled from parameter store to be used for application instances
      OutputsPrefix:
        default: The prefix for stack outputs that will be used for your pipeline resources
Resources:
  #Code Repository for the simple Calculator application (CodeCommit Repo)
  CodeCommitRepo:
    Type: "AWS::CodeCommit::Repository"
    Properties:
      RepositoryName: !Ref EnvironmentName
      RepositoryDescription: "Calculator application repository"
      Code:
        S3:
          Bucket: !Sub ${codeBucket}
          Key: calculator.zip

  # Shared Network Resources for the application environments
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName} VPC"
  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
      - Key: Name
        Value: !Sub "${EnvironmentName} IG"
  InternetGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ""
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub '${EnvironmentName} Public Subnet 1'
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs: ""
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub '${ApplicationName} Public Subnet 2'
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ""
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: !Sub '${ApplicationName} Private Subnet 1'
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc
  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet2
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub '${EnvironmentName} Public Routes'
